-- Application-owned tables that are not part of the imported KBO schema.

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL,
    display_name character varying(50) NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
    ON public.users (LOWER(email));

-- 이전 버전에서 이미 중복 생성된 닉네임은 최초 계정만 유지하고,
-- 이후 계정에는 사용자 ID를 붙여 고유하게 만든다.
WITH duplicate_names AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY LOWER(display_name)
               ORDER BY id
           ) AS duplicate_order
    FROM public.users
)
UPDATE public.users AS u
SET display_name = LEFT(u.display_name, 20)
                   || '_' || u.id::text
                   || '_' || LEFT(MD5(u.email), 6)
FROM duplicate_names AS d
WHERE u.id = d.id
  AND d.duplicate_order > 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_display_name_lower
    ON public.users (LOWER(display_name));

CREATE TABLE IF NOT EXISTS public.game_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
    team_name character varying(100) NOT NULL,
    opponent_name character varying(100) NOT NULL,
    result character varying(10) NOT NULL,
    my_score integer NOT NULL,
    opp_score integer NOT NULL,
    played_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT game_records_result_check
        CHECK (result IN ('승', '패', '무')),
    CONSTRAINT game_records_my_score_check
        CHECK (my_score >= 0),
    CONSTRAINT game_records_opp_score_check
        CHECK (opp_score >= 0)
);

-- 기존 Docker 볼륨의 game_records에도 사용자 소유권 컬럼을 추가한다.
ALTER TABLE public.game_records
    ADD COLUMN IF NOT EXISTS user_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'game_records_user_id_fkey'
          AND conrelid = 'public.game_records'::regclass
    ) THEN
        ALTER TABLE public.game_records
            ADD CONSTRAINT game_records_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_game_records_team_played_at
    ON public.game_records (team_name, played_at DESC);

CREATE INDEX IF NOT EXISTS idx_game_records_user_played_at
    ON public.game_records (user_id, played_at DESC);
