-- Application-owned tables that are not part of the imported KBO schema.

CREATE TABLE IF NOT EXISTS public.game_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name character varying(100) NOT NULL,
    opponent_name character varying(100) NOT NULL,
    result character varying(10) NOT NULL,
    my_score integer NOT NULL,
    opp_score integer NOT NULL,
    played_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT game_records_result_check
        CHECK (result IN ('승', '패', '무')),
    CONSTRAINT game_records_my_score_check
        CHECK (my_score >= 0),
    CONSTRAINT game_records_opp_score_check
        CHECK (opp_score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_game_records_team_played_at
    ON public.game_records (team_name, played_at DESC);
